# Generated by Django 3.0.4 on 2020-05-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
